apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "1st deploy"
  creationTimestamp: null
  labels:
    env: dev
  name: firstdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        env: dev
    spec:
      containers:
      - image: coolgourav147/nginx-custom:v1
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
