apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-custom
  name: nginx-custom
spec:
  containers:
  - image: coolgourav147/nginx-custom
    name: nginx-custom
    resources: 
      limits: 
        memory: 5Gi
      requests:
        memory: 4Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
