apiVersion: v1
kind: LimitRange
metadata:
    name: testlimit
    namespace: myns
spec:
  limits:
      - default:
          cpu: 200m
          memory: 400Mi
        defaultRequest:
          cpu: 100m
          memory: 250Mi
        min:
          cpu: 88m
          memory: 250Mi
        max:
          cpu: 1000m
          memory: 1Gi
        type: Container
