apiVersion: v1
kind: Pod

metadata:
  name: myfirstpod
  labels:
    env1: dev
    env: prod

spec:
  containers:
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      env:
        - name: debi
          value: BBSR
        - name: rajendra
          value: deogarh
      # args: ["sleep", "3600"] //used it for testing purpose
    - name: secondcontainer
      image: coolgourav147/nginx-custom
