apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-fifth
  labels:
    app: myapp4
spec:
  containers:
  - name: nginx-con
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests: 
        cpu: 0.2
        memory: 150Mi
      limits: 
        cpu: 0.5
        memory: 250Mi