apiVersion: v1
kind: ReplicationController

metadata:
  name: rc1
  labels:
    env: prod

spec:
  replicas: 5
  template:
    metadata:
      name: firstpod1
      labels:
        type: app
    spec:
      containers:
      - name: container1
        image: coolgourav147/nginx-custom