apiVersion: v1 
kind: ConfigMap

metadata:
  name: cm1
  creationTimestamp: 2022-11-14T18:54:22Z
  namespace: myns

data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
  SPECIAL_POWER: max



---

apiVersion: v1 
kind: ConfigMap

metadata: 
  name: cm2
  creationTimestamp: 2022-11-14T18:55:22Z
  namespace: myns

data:
  SPECIAL_ABILITY: auto 
  SPECIAL_SHRED: hyper
  SPECIAL_GROUND: up
