apiVersion: v1
data:
  username: ZGViaXByYXNhZA==
  password: dXNlcnB3ZA==
kind: Secret
metadata:
  creationTimestamp: "2022-11-15T08:06:58Z"
  name: mysec
  namespace: default
  resourceVersion: "150015"
  uid: 29b9c023-5808-4a79-a830-4defad4e2c77
type: Opaque

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  
    - image: coolgourav147/nginx-custom
      name: pod
      
      
      env: 
        - name: secretusername
          valueFrom:
              secretKeyRef:
                name: mysec
                key: username

        - name: secretuserpwd
          valueFrom:
              secretKeyRef:
                name: mysec
                key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
