apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - args:
    - pod6
    image: coolgourav147/nginx-custom
    name: pod
    env: 
        - name: secretusername
          valueFrom:
              secretKeyRef:
                name: mysec
                key: username

        - name: secretuserpwd
          valueFrom:
              secretKeyRef:
                name: mysec
                key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
